import { getFrameMetadata } from "@coinbase/onchainkit/core";
import type { Metadata } from "next";

const frameMetadata = getFrameMetadata({
  buttons:[
    {
      label: "Begin",
    }
  ],
  image: `${process.env.NEXT_PUBLIC_GATEWAY_URL}/img/QmRaTSD5nFJvLZp83AcmJZ8HbbzD1PcXLjeLgVy1kKHWem/`,
  post_url: `${process.env.NEXT_PUBLIC_BASE_URL}/api/frame?id=1`,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph:{
    title: "Create Next App",
    description: "Generated by create next app",
    images: [`${process.env.NEXT_PUBLIC_GATEWAY_URL}/img/QmRaTSD5nFJvLZp83AcmJZ8HbbzD1PcXLjeLgVy1kKHWem/`],
  },
  other:{
    ...frameMetadata
  }
}

export default function Home() {
  return <div className="">Car/City/Code</div>;
}
